universe = vanilla

Executable =/afs/cern.ch/user/m/matheus/CMSSW_10_6_24/src/submit.sh

+JobFlavour="nextweek"

when_to_transfer_output = ON_EXIT
should_transfer_files = IF_NEEDED

transfer_input_files = /afs/cern.ch/user/m/matheus/CMSSW_10_6_24/src/ntuple_mc_2018_cfg.py, /afs/cern.ch/user/m/matheus/CMSSW_10_6_24/src/submit.sh

output = output/$(ClusterId)_$(ProcId).out
error  = output/$(ClusterId)_$(ProcId).err
log    = output/$(ClusterId)_$(ProcId).log

getenv=true
RequestCpus = 4

max_retries = 1

queue arguments from /afs/cern.ch/user/m/matheus/CMSSW_10_6_24/src/remoteFileList.txt
